In [1]:
import pandas as pd
import numpy as np

users = pd.read_csv("../data/raw/users.csv")
products = pd.read_csv("../data/raw/products.csv")
sessions = pd.read_csv("../data/raw/sessions.csv")
events = pd.read_csv("../data/raw/events.csv")
orders = pd.read_csv("../data/raw/orders.csv")
experiment = pd.read_csv("../data/raw/experiment_assignment.csv")

In [2]:
print(users.shape)
print(products.shape)
print(sessions.shape)
print(events.shape)
print(orders.shape)
print(experiment.shape)

(120000, 11)
(500, 12)
(659860, 15)
(1974752, 5)
(44176, 15)
(120000, 4)

In [3]:
for name, df in {
    "users": users,
    "products": products,
    "sessions": sessions,
    "events": events,
    "orders": orders,
    "experiment": experiment
}.items():
    print("=" * 50)
    print(name)
    print("=" * 50)
    df.info()
    display(df.describe(include="all"))
    display(df.head())

==================================================
users
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   user_id           120000 non-null  object
 1   signup_date       120000 non-null  object
 2   country           120000 non-null  object
 3   city              120000 non-null  object
 4   age               120000 non-null  int64
 5   gender            120000 non-null  object
 6   customer_type     120000 non-null  object
 7   premium_member    120000 non-null  bool
 8   signup_channel    120000 non-null  object
 9   lifetime_value    120000 non-null  float64
 10  preferred_device  120000 non-null  object
dtypes: bool(1), float64(1), int64(1), object(8)
memory usage: 9.3+ MB

,user_id,signup_date,country,city,age,gender,customer_type,premium_member,signup_channel,lifetime_value,preferred_device
count,120000,120000,120000,120000,120000.000000,120000,120000,120000,120000,120000.000000,120000
unique,120000,1247,6,30,NaN,3,2,2,5,NaN,3
top,USR_119984,2025-06-04,Canada,Ottawa,NaN,Male,New,False,Social,NaN,Mobile
freq,1,123,20216,4140,NaN,57943,72187,95953,24242,NaN,66047
mean,NaN,NaN,NaN,NaN,35.281675,NaN,NaN,NaN,NaN,114.968641,NaN
std,NaN,NaN,NaN,NaN,10.402259,NaN,NaN,NaN,NaN,86.205736,NaN
min,NaN,NaN,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,0.320000,NaN
25%,NaN,NaN,NaN,NaN,28.000000,NaN,NaN,NaN,NaN,54.430000,NaN
50%,NaN,NaN,NaN,NaN,35.000000,NaN,NaN,NaN,NaN,93.875000,NaN
75%,NaN,NaN,NaN,NaN,42.000000,NaN,NaN,NaN,NaN,151.760000,NaN
max,NaN,NaN,NaN,NaN,70.000000,NaN,NaN,NaN,NaN,1018.800000,NaN

,user_id,signup_date,country,city,age,gender,customer_type,premium_member,signup_channel,lifetime_value,preferred_device
0,USR_000001,2025-08-23,India,Hyderabad,32,Male,New,False,Paid_Ads,129.32,Mobile
1,USR_000002,2024-07-01,Germany,Munich,40,Male,New,False,Social,160.82,Desktop
2,USR_000003,2025-12-06,India,Bangalore,52,Male,New,False,Social,168.13,Desktop
3,USR_000004,2025-05-19,Canada,Ottawa,25,Female,Returning,False,Social,137.40,Desktop
4,USR_000005,2023-04-28,India,Mumbai,41,Male,New,False,Organic,137.46,Mobile

==================================================
products
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_id        500 non-null    object
 1   product_name      500 non-null    object
 2   category          500 non-null    object
 3   subcategory       500 non-null    object
 4   brand             500 non-null    object
 5   price             500 non-null    float64
 6   cost              500 non-null    float64
 7   discount_percent  500 non-null    int64
 8   rating            500 non-null    float64
 9   stock_quantity    500 non-null    int64
 10  seller            500 non-null    object
 11  launch_date       500 non-null    object
dtypes: float64(3), int64(2), object(7)
memory usage: 47.0+ KB

,product_id,product_name,category,subcategory,brand,price,cost,discount_percent,rating,stock_quantity,seller,launch_date
count,500,500,500,500,500,500.000000,500.000000,500.00000,500.000000,500.000000,500,500
unique,500,500,6,29,12,NaN,NaN,NaN,NaN,NaN,6,457
top,PRD_000500,Vireo_Fitness_500,Home,Accessories,Marlow,NaN,NaN,NaN,NaN,NaN,TopDeals_Co,2024-05-12
freq,1,1,100,29,50,NaN,NaN,NaN,NaN,NaN,93,3
mean,NaN,NaN,NaN,NaN,NaN,254.101720,151.699520,10.15000,3.769800,1016.108000,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,308.909425,184.903846,9.34892,0.711224,581.099511,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,5.280000,2.710000,0.00000,1.300000,2.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,50.002500,29.585000,0.00000,3.300000,528.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,142.820000,82.600000,10.00000,3.900000,1022.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,334.550000,198.865000,15.00000,4.300000,1536.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,1499.580000,1012.400000,30.00000,5.000000,1998.000000,NaN,NaN

,product_id,product_name,category,subcategory,brand,price,cost,discount_percent,rating,stock_quantity,seller,launch_date
0,PRD_000001,Pinegrove_Fragrance_1,Beauty,Fragrance,Pinegrove,118.55,86.17,5,3.4,472,ShopSmart_Official,2025-05-07
1,PRD_000002,Urbanix_Haircare_2,Beauty,Haircare,Urbanix,23.91,16.92,10,4.8,1555,ShopSmart_Official,2022-05-25
2,PRD_000003,Lumo_Tools_3,Beauty,Tools,Lumo,8.60,5.54,15,4.0,1495,PartnerHub,2021-07-12
3,PRD_000004,Marlow_Children_4,Books,Children,Marlow,36.39,20.36,0,4.2,573,ValueMart,2020-01-23
4,PRD_000005,Northfield_Fragrance_5,Beauty,Fragrance,Northfield,16.89,11.18,15,3.8,709,ValueMart,2023-11-19

==================================================
sessions
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 659860 entries, 0 to 659859
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   session_id        659860 non-null  object
 1   user_id           659860 non-null  object
 2   session_start     659860 non-null  object
 3   session_end       659860 non-null  object
 4   device            656608 non-null  object
 5   browser           653200 non-null  object
 6   operating_system  659860 non-null  object
 7   traffic_source    659860 non-null  object
 8   landing_page      659860 non-null  object
 9   country           659860 non-null  object
 10  city              659860 non-null  object
 11  is_returning      659860 non-null  bool
 12  session_duration  659860 non-null  float64
 13  pages_viewed      659860 non-null  int64
 14  bounce            659860 non-null  bool
dtypes: bool(2), float64(1), int64(1), object(11)
memory usage: 66.7+ MB

,session_id,user_id,session_start,session_end,device,browser,operating_system,traffic_source,landing_page,country,city,is_returning,session_duration,pages_viewed,bounce
count,659860,659860,659860,659860,656608,653200,659860,659860,659860,659860,659860,659860,659860.000000,659860.000000,659860
unique,659860,120000,645938,646205,3,5,5,6,5,6,30,2,NaN,NaN,2
top,SES_0659860,USR_119975,2026-04-21 10:36:07,2026-02-02 16:52:50,Mobile,Chrome,Windows,Organic,Homepage,Canada,Ottawa,False,NaN,NaN,False
freq,1,10,4,4,361856,359749,230844,197793,297447,111779,23077,396936,NaN,NaN,528344
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,231.593507,5.803002,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,182.005034,3.122383,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,1.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113.140000,4.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,181.460000,6.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,290.980000,8.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1800.000000,19.000000,NaN

,session_id,user_id,session_start,session_end,device,browser,operating_system,traffic_source,landing_page,country,city,is_returning,session_duration,pages_viewed,bounce
0,SES_0000001,USR_000001,2026-01-11 11:24:38,2026-01-11 11:35:02,Mobile,Safari,iOS,Organic,Search,India,Hyderabad,False,624.36,1,True
1,SES_0000002,USR_000002,2026-03-28 12:56:45,2026-03-28 12:59:26,Desktop,Chrome,Windows,Referral,Homepage,Germany,Munich,False,161.21,7,False
2,SES_0000003,USR_000002,2026-02-10 16:33:15,2026-02-10 16:35:38,Mobile,Edge,Android,Social,Homepage,Germany,Munich,False,143.09,5,False
3,SES_0000004,USR_000002,2026-01-13 09:27:39,2026-01-13 09:30:46,Mobile,Firefox,macOS,Email,Search,Germany,Munich,False,187.51,8,False
4,SES_0000005,USR_000002,2026-04-12 02:26:20,2026-04-12 02:27:38,Mobile,Chrome,macOS,Social,Homepage,Germany,Munich,False,78.82,5,False

==================================================
events
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1974752 entries, 0 to 1974751
Data columns (total 5 columns):
 #   Column          Dtype
---  ------          -----
 0   event_id        object
 1   session_id      object
 2   event_name      object
 3   event_sequence  int64
 4   event_time      object
dtypes: int64(1), object(4)
memory usage: 75.3+ MB

,event_id,session_id,event_name,event_sequence,event_time
count,1974752,1974752,1974752,1.974752e+06,1974752
unique,1974752,659860,10,NaN,1854969
top,EVT_001974736,SES_0070841,Homepage,NaN,2026-04-27 15:14:06
freq,1,9,659860,NaN,6
mean,NaN,NaN,NaN,2.739611e+00,NaN
std,NaN,NaN,NaN,1.922133e+00,NaN
min,NaN,NaN,NaN,1.000000e+00,NaN
25%,NaN,NaN,NaN,1.000000e+00,NaN
50%,NaN,NaN,NaN,2.000000e+00,NaN
75%,NaN,NaN,NaN,4.000000e+00,NaN
max,NaN,NaN,NaN,9.000000e+00,NaN

        event_id   session_id event_name  event_sequence           event_time
0  EVT_000000001  SES_0000001   Homepage               1  2026-01-11 11:24:38
1  EVT_000000002  SES_0000002   Homepage               1  2026-03-28 12:56:45
2  EVT_000000003  SES_0000003   Homepage               1  2026-02-10 16:33:15
3  EVT_000000004  SES_0000003     Search               2  2026-02-10 16:34:26
4  EVT_000000005  SES_0000004   Homepage               1  2026-01-13 09:27:39

==================================================
orders
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44176 entries, 0 to 44175
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        44176 non-null  object
 1   user_id         44176 non-null  object
 2   session_id      44176 non-null  object
 3   product_id      44176 non-null  object
 4   quantity        44176 non-null  int64
 5   unit_price      44176 non-null  float64
 6   discount        44176 non-null  float64
 7   coupon_used     44176 non-null  bool
 8   payment_method  44176 non-null  object
 9   shipping_cost   44176 non-null  float64
 10  tax             44176 non-null  float64
 11  total_amount    44176 non-null  float64
 12  profit          44176 non-null  float64
 13  purchase_time   44176 non-null  object
 14  order_status    44176 non-null  object
dtypes: bool(1), float64(6), int64(1), object(7)
memory usage: 4.8+ MB

,order_id,user_id,session_id,product_id,quantity,unit_price,discount,coupon_used,payment_method,shipping_cost,tax,total_amount,profit,purchase_time,order_status
count,44176,44176,44176,44176,44176.000000,44176.000000,44176.000000,44176,44176,44176.000000,44176.000000,44176.000000,44176.000000,44176,44176
unique,44176,36421,44176,500,NaN,NaN,NaN,2,6,NaN,NaN,NaN,NaN,44115,3
top,ORD_044160,USR_094041,SES_0659600,PRD_000125,NaN,NaN,NaN,False,Card,NaN,NaN,NaN,NaN,2026-06-16 20:03:37,Completed
freq,1,5,1,117,NaN,NaN,NaN,33030,13012,NaN,NaN,NaN,NaN,2,39921
mean,NaN,NaN,NaN,NaN,2.385141,255.129986,69.509317,NaN,NaN,0.822372,43.186850,583.844329,156.833764,NaN,NaN
std,NaN,NaN,NaN,NaN,1.160228,308.029878,147.781512,NaN,NaN,2.036771,61.928521,835.494835,307.147962,NaN,NaN
min,NaN,NaN,NaN,NaN,1.000000,5.280000,0.000000,NaN,NaN,0.000000,0.320000,7.560000,-3266.480000,NaN,NaN
25%,NaN,NaN,NaN,NaN,2.000000,51.210000,1.890000,NaN,NaN,0.000000,7.050000,95.210000,16.190000,NaN,NaN
50%,NaN,NaN,NaN,NaN,2.000000,144.170000,19.380000,NaN,NaN,0.000000,20.310000,274.230000,64.045000,NaN,NaN
75%,NaN,NaN,NaN,NaN,3.000000,337.360000,70.600000,NaN,NaN,0.000000,53.222500,718.475000,193.290000,NaN,NaN
max,NaN,NaN,NaN,NaN,6.000000,1499.580000,2668.330000,NaN,NaN,8.000000,653.540000,8822.780000,4480.140000,NaN,NaN

,order_id,user_id,session_id,product_id,quantity,unit_price,discount,coupon_used,payment_method,shipping_cost,tax,total_amount,profit,purchase_time,order_status
0,ORD_000001,USR_000002,SES_0000007,PRD_000329,1,160.32,24.05,False,Card,0.0,10.90,147.17,42.21,2026-05-24 07:25:25,Completed
1,ORD_000002,USR_000006,SES_0000021,PRD_000318,2,159.85,44.93,True,One_Click_Wallet,0.0,21.98,296.75,73.93,2026-05-05 12:43:46,Completed
2,ORD_000003,USR_000017,SES_0000080,PRD_000251,2,111.87,44.75,False,NetBanking,0.0,14.32,193.31,74.91,2026-06-29 13:25:51,Completed
3,ORD_000004,USR_000018,SES_0000083,PRD_000188,2,106.80,20.85,True,Card,0.0,15.42,208.17,77.43,2026-05-14 17:26:09,Cancelled
4,ORD_000005,USR_000020,SES_0000095,PRD_000484,4,159.90,0.00,False,One_Click_Card,0.0,51.17,690.77,271.84,2026-04-23 06:24:41,Completed

==================================================
experiment
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   assignment_id    120000 non-null  object
 1   user_id          120000 non-null  object
 2   experiment_name  120000 non-null  object
 3   group            120000 non-null  object
dtypes: object(4)
memory usage: 3.7+ MB

       assignment_id     user_id             experiment_name    group
count         120000      120000                      120000   120000
unique        120000      120000                           1        2
top       ASG_119984  USR_119984  EXP_CHECKOUT_REDESIGN_2026  Control
freq               1           1                      120000    60000

  assignment_id     user_id             experiment_name      group
0    ASG_000001  USR_000001  EXP_CHECKOUT_REDESIGN_2026    Control
1    ASG_000002  USR_000002  EXP_CHECKOUT_REDESIGN_2026  Treatment
2    ASG_000003  USR_000003  EXP_CHECKOUT_REDESIGN_2026  Treatment
3    ASG_000004  USR_000004  EXP_CHECKOUT_REDESIGN_2026  Treatment
4    ASG_000005  USR_000005  EXP_CHECKOUT_REDESIGN_2026  Treatment

In [4]:
for name, df in {
    "users": users,
    "products": products,
    "sessions": sessions,
    "events": events,
    "orders": orders,
    "experiment": experiment
}.items():

    print("\n", "=" * 50)
    print(name)
    print("=" * 50)
    print(df.isnull().sum())

 ==================================================
users
==================================================
user_id             0
signup_date         0
country             0
city                0
age                 0
gender              0
customer_type       0
premium_member      0
signup_channel      0
lifetime_value      0
preferred_device    0
dtype: int64

 ==================================================
products
==================================================
product_id          0
product_name        0
category            0
subcategory         0
brand               0
price               0
cost                0
discount_percent    0
rating              0
stock_quantity      0
seller              0
launch_date         0
dtype: int64

 ==================================================
sessions
==================================================
session_id             0
user_id                0
session_start          0
session_end            0
device              3252
browser             6660
operating_system       0
traffic_source         0
landing_page           0
country                0
city                   0
is_returning           0
session_duration       0
pages_viewed           0
bounce                 0
dtype: int64

 ==================================================
events
==================================================
event_id          0
session_id        0
event_name        0
event_sequence    0
event_time        0
dtype: int64

 ==================================================
orders
==================================================
order_id          0
user_id           0
session_id        0
product_id        0
quantity          0
unit_price        0
discount          0
coupon_used       0
payment_method    0
shipping_cost     0
tax               0
total_amount      0
profit            0
purchase_time     0
order_status      0
dtype: int64

 ==================================================
experiment
==================================================
assignment_id      0
user_id            0
experiment_name    0
group              0
dtype: int64

In [5]:
for name, df in {
    "users": users,
    "products": products,
    "sessions": sessions,
    "events": events,
    "orders": orders,
    "experiment": experiment
}.items():

    print(name, "duplicates:", df.duplicated().sum())

users duplicates: 0
products duplicates: 0
sessions duplicates: 0
events duplicates: 0
orders duplicates: 0
experiment duplicates: 0

In [6]:
print("Users:", users["user_id"].nunique(), users.shape[0])
print("Products:", products["product_id"].nunique(), products.shape[0])
print("Sessions:", sessions["session_id"].nunique(), sessions.shape[0])
print("Events:", events["event_id"].nunique(), events.shape[0])
print("Orders:", orders["order_id"].nunique(), orders.shape[0])
print("Assignments:", experiment["assignment_id"].nunique(), experiment.shape[0])

Users: 120000 120000
Products: 500 500
Sessions: 659860 659860
Events: 1974752 1974752
Orders: 44176 44176
Assignments: 120000 120000

In [7]:
invalid_sessions = sessions[
    ~sessions["user_id"].isin(users["user_id"])
]

print(len(invalid_sessions))

0

In [8]:
invalid_events = events[
    ~events["session_id"].isin(sessions["session_id"])
]

print(len(invalid_events))

0

In [9]:
invalid_orders_users = orders[
    ~orders["user_id"].isin(users["user_id"])
]

print(len(invalid_orders_users))

0

In [10]:
invalid_orders_sessions = orders[
    ~orders["session_id"].isin(sessions["session_id"])
]

print(len(invalid_orders_sessions))

0

In [11]:
invalid_orders_products = orders[
    ~orders["product_id"].isin(products["product_id"])
]

print(len(invalid_orders_products))

0

In [12]:
users["signup_date"] = pd.to_datetime(
    users["signup_date"],
    errors="coerce"
)

sessions["session_start"] = pd.to_datetime(
    sessions["session_start"],
    errors="coerce"
)

sessions["session_end"] = pd.to_datetime(
    sessions["session_end"],
    errors="coerce"
)

events["event_time"] = pd.to_datetime(
    events["event_time"],
    errors="coerce"
)

orders["purchase_time"] = pd.to_datetime(
    orders["purchase_time"],
    errors="coerce"
)

products["launch_date"] = pd.to_datetime(
    products["launch_date"],
    errors="coerce"
)

In [13]:
events.dtypes

event_id                  object
session_id                object
event_name                object
event_sequence             int64
event_time        datetime64[ns]
dtype: object

In [14]:
print("Invalid event timestamps:",
      events["event_time"].isna().sum())

print("Invalid order timestamps:",
      orders["purchase_time"].isna().sum())

Invalid event timestamps: 0
Invalid order timestamps: 0

In [15]:
invalid_sessions = sessions[
    sessions["session_end"] < sessions["session_start"]
]

print(len(invalid_sessions))

0

In [16]:
print(orders[orders["quantity"] <= 0])
print(orders[orders["unit_price"] < 0])
print(orders[orders["total_amount"] < 0])
print(products[products["price"] < 0])

Empty DataFrame
Columns: [order_id, user_id, session_id, product_id, quantity, unit_price, discount, coupon_used, payment_method, shipping_cost, tax, total_amount, profit, purchase_time, order_status]
Index: []
Empty DataFrame
Columns: [order_id, user_id, session_id, product_id, quantity, unit_price, discount, coupon_used, payment_method, shipping_cost, tax, total_amount, profit, purchase_time, order_status]
Index: []
Empty DataFrame
Columns: [order_id, user_id, session_id, product_id, quantity, unit_price, discount, coupon_used, payment_method, shipping_cost, tax, total_amount, profit, purchase_time, order_status]
Index: []
Empty DataFrame
Columns: [product_id, product_name, category, subcategory, brand, price, cost, discount_percent, rating, stock_quantity, seller, launch_date]
Index: []

In [17]:
print(products[
    (products["rating"] < 0) |
    (products["rating"] > 5)
])

Empty DataFrame
Columns: [product_id, product_name, category, subcategory, brand, price, cost, discount_percent, rating, stock_quantity, seller, launch_date]
Index: []

In [18]:
experiment["group"].value_counts()

group
Control      60000
Treatment    60000
Name: count, dtype: int64

In [19]:
experiment["group"].value_counts(normalize=True) * 100

group
Control      50.0
Treatment    50.0
Name: proportion, dtype: float64

In [20]:
balance = experiment.merge(
    users,
    on="user_id",
    how="left"
)

balance.groupby("group")["age"].mean()

group
Control      35.28260
Treatment    35.28075
Name: age, dtype: float64

In [21]:
pd.crosstab(
    balance["group"],
    balance["preferred_device"],
    normalize="index"
) * 100

preferred_device    Desktop     Mobile    Tablet
group
Control           35.366667  54.796667  9.836667
Treatment         34.940000  55.281667  9.778333

In [22]:
pd.crosstab(
    balance["group"],
    balance["premium_member"],
    normalize="index"
) * 100

premium_member      False      True
group
Control         80.000000  20.000000
Treatment       79.921667  20.078333